name: maulajimessenger
description: Maulaji Talk

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1


environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: "^2.0.4"
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.1.1
  google_sign_in: ^5.0.2
  flutter_signin_button: ^2.0.0
  firebase_core: ^1.0.4
  firebase_dynamic_links: ^2.0.1
  #cloud_firestore: ^1.0.6
  image: ^3.0.2
  http: ^0.13.1
  intl: ^0.17.0
  clipboard: ^0.1.2+8
  fluttertoast: ^7.1.1
  bubble: ^1.1.9+1

  flutter_webrtc:
  sdp_transform: ^0.3.0
  audioplayers: ^0.18.3
  path_provider: ^2.0.1
  country_list_pick:
  #web_socket_channel: ^2.0.0

  #socket_io_client: ^1.0.1
  socket_io_client: ^2.0.0-beta.4
  #socket_io: ^1.0.0
  file_picker:
  shared_preferences:
  #emoji_picker:
  #flutter_emoji:
  #emoji_pick: ^0.1.0
  video_player: ^2.1.1
  emojis:
  #drop_zone:
  #emoji_chooser:
  #jitsi_meet: ^4.0.0
  #drop_zone:
  line_icons:
  web_socket_channel: ^2.1.0
  country_code_picker: ^2.0.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/no_photo.png
    - assets/skype-ringtone.mp3
    - assets/passive.mp3
    - assets/maulaji_sqr.png
    - assets/background.png
    - assets/splash_app.jpg
    - assets/app_icon.png
    - assets/user_photo.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/poppins.otf

    - family: SF Pro Display Regular
      fonts:
        - asset: assets/sf_pro.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

